import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { LayoutDashboard, BookOpen, ClipboardCheck, Flame, BarChart3, Search, Bell, ChevronRight, Clock3, Target, Trophy, Menu, X, CheckCircle2, Circle, ArrowRight, Bookmark, Play, Zap, TrendingUp, FileText, ListChecks, LockKeyhole } from 'lucide-react'
import './styles.css'

const subjects = [
  ['History','इतिहास','#f97316','Mug'],['Geography','भूगोल','#38bdf8','Map'],['Polity','राजव्यवस्था','#a78bfa','Scale'],['Science','विज्ञान','#22c55e','Atom'],
  ['Economy','अर्थव्यवस्था','#facc15','Coins'],['Hindi','हिंदी','#fb7185','A'],['Maths','गणित','#2dd4bf','∑'],['Reasoning','रीजनिंग','#818cf8','◈'],['UP GK','उत्तर प्रदेश GK','#f97316','UP']
]
const questions = [
  {q:'भारतीय संविधान कब लागू हुआ?', options:['15 अगस्त 1947','26 नवंबर 1949','26 जनवरी 1950','15 अगस्त 1950'], answer:2, explanation:'भारतीय संविधान 26 नवंबर 1949 को अपनाया गया और 26 जनवरी 1950 को लागू हुआ।', subject:'Polity'},
  {q:'भारत का सबसे बड़ा राज्य क्षेत्रफल की दृष्टि से कौन सा है?', options:['मध्य प्रदेश','राजस्थान','महाराष्ट्र','उत्तर प्रदेश'], answer:1, explanation:'राजस्थान 3,42,239 वर्ग किमी क्षेत्रफल के साथ भारत का सबसे बड़ा राज्य है।', subject:'Geography'},
  {q:'पानी का रासायनिक सूत्र क्या है?', options:['CO₂','H₂O','O₂','NaCl'], answer:1, explanation:'जल का एक अणु दो हाइड्रोजन और एक ऑक्सीजन परमाणु से बना होता है।', subject:'Science'},
]
const examCards = [['UPSSSC PET','#ff6a00','500+ MCQs'],['SSC GD','#38bdf8','500+ MCQs'],['SSC MTS','#a78bfa','500+ MCQs'],['Army GD','#22c55e','250+ MCQs'],['Army Agniveer','#facc15','250+ MCQs'],['BSF Tradesman','#fb7185','250+ MCQs'],['UP Police','#f97316','500+ MCQs'],['MP Police','#60a5fa','500+ MCQs'],['State Police','#c084fc','500+ MCQs']]

function App(){
 const [page,setPage]=useState('Dashboard'); const [mobile,setMobile]=useState(false); const [activeQ,setActiveQ]=useState(0); const [selected,setSelected]=useState(null); const [started,setStarted]=useState(false)
 const nav=[['Dashboard',LayoutDashboard],['Practice MCQ',BookOpen],['Mock Tests',ClipboardCheck],['Topics',ListChecks],['Notes',FileText],['Syllabus',LockKeyhole],['Daily Practice',Flame],['Progress',BarChart3]]
 const q=questions[activeQ]
 return <div className="app-shell">
  <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><div className="brand-mark">P</div><div><b>PET<span>PREP</span></b><small>UPSSSC • 2025</small></div><button className="close" onClick={()=>setMobile(false)}><X size={20}/></button></div><div className="side-label">MAIN MENU</div><nav>{nav.map(([name,Icon])=><button className={page===name?'active':''} onClick={()=>{setPage(name);setMobile(false)}} key={name}><Icon size={19}/>{name}{name==='Practice MCQ'&&<em>500+</em>}</button>)}</nav><div className="side-card"><Zap size={20}/><b>Keep the streak alive!</b><span>Practice 20 questions today.</span><button onClick={()=>setPage('Daily Practice')}>Start now <ArrowRight size={14}/></button></div><div className="profile"><div className="avatar">A</div><div><b>Anshul Kumar</b><span>Pro learner</span></div><ChevronRight size={16}/></div></aside>
  <main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb"><span>Workspace</span><ChevronRight size={14}/><b>{page}</b></div><div className="header-actions"><div className="search"><Search size={17}/><input placeholder="Search topics, tests..."/></div><button className="icon-btn"><Bell size={19}/><i/></button><div className="top-avatar">AK</div></div></header>
   {page==='Dashboard'&&<><Dashboard setPage={setPage}/><ExamHub setPage={setPage}/></>} {page==='Practice MCQ'&&<Practice subjects={subjects} q={q} activeQ={activeQ} setActiveQ={setActiveQ} selected={selected} setSelected={setSelected} started={started} setStarted={setStarted}/>} {page==='Mock Tests'&&<Mock setPage={setPage}/>} {page==='Topics'&&<Topics setPage={setPage}/>} {page==='Notes'&&<Notes/>} {page==='Syllabus'&&<Syllabus/>} {page==='Daily Practice'&&<Practice daily subjects={subjects} q={q} activeQ={activeQ} setActiveQ={setActiveQ} selected={selected} setSelected={setSelected} started={started} setStarted={setStarted}/>} {page==='Progress'&&<Progress/>}
  </main></div>
}
function Dashboard({setPage}){return <section className="content"><div className="hero"><div><div className="eyebrow">TUESDAY, 22 SEPTEMBER 2026</div><h1>Namaste, Anshul <span>👋</span></h1><p>Ready to make today's progress count?</p></div><button className="orange-btn" onClick={()=>setPage('Practice MCQ')}><Play size={16} fill="currentColor"/> Continue practice</button></div><div className="stat-grid"><Stat icon={Target} label="Overall progress" value="68%" sub="+12% this week"/><Stat icon={BookOpen} label="Questions attempted" value="1,248" sub="of 2,000 questions"/><Stat icon={Trophy} label="Average accuracy" value="78.4%" sub="+4.2% this week"/><Stat icon={Clock3} label="Study time" value="24h 18m" sub="This month"/></div><div className="dashboard-grid"><div className="panel focus"><div className="panel-head"><div><h2>Continue where you left off</h2><p>Your last practice session</p></div><button className="text-btn" onClick={()=>setPage('Practice MCQ')}>View all <ArrowRight size={15}/></button></div><div className="continue-row"><div className="subject-icon orange">◈</div><div className="grow"><b>Indian Polity • Fundamental Rights</b><span>Question 18 of 30 <i>•</i> 12 min left</span><div className="progress"><i style={{width:'60%'}}/></div></div><button className="round-btn" onClick={()=>setPage('Practice MCQ')}><ArrowRight size={18}/></button></div></div><div className="panel streak"><div className="streak-top"><div><h2>Daily streak</h2><p>You're on fire!</p></div><Flame size={30} className="flame" fill="currentColor"/></div><div className="streak-number">7 <small>days</small></div><div className="days">{['M','T','W','T','F','S','S'].map((d,i)=><span className={i<5?'done':''} key={i}>{i<5?'✓':d}</span>)}</div></div></div><div className="section-title"><div><h2>Practice by subject</h2><p>Build confidence, one topic at a time</p></div><button className="text-btn" onClick={()=>setPage('Practice MCQ')}>All subjects <ArrowRight size={15}/></button></div><div className="subject-grid">{subjects.slice(0,6).map(([a,b,c,ic])=><button className="subject-card" key={a} onClick={()=>setPage('Practice MCQ')}><div className="subject-icon" style={{color:c,background:c+'18'}}>{ic}</div><b>{a}</b><span>{b}</span><div className="mini-progress"><i style={{width:Math.floor(Math.random()*40+45)+'%',background:c}}/></div><small>124 questions <ChevronRight size={13}/></small></button>)}</div></section>}
function Stat({icon:Icon,label,value,sub}){return <div className="stat"><div className="stat-icon"><Icon size={19}/></div><span>{label}</span><b>{value}</b><small>{sub}</small></div>}
function ExamHub({setPage}){return <section className="content exam-hub"><div className="section-title"><div><h2>Choose your exam</h2><p>Prepare for multiple government exams in one place</p></div><button className="text-btn" onClick={()=>setPage('Mock Tests')}>All mock tests <ArrowRight size={15}/></button></div><div className="exam-grid">{examCards.map(([name,color,count])=><button className="exam-card" key={name} onClick={()=>setPage('Mock Tests')}><div className="exam-logo" style={{background:color+'18',color}}><img src="/anshulogo.jpg" alt=""/></div><div><b>{name}</b><span>{count}</span></div><ChevronRight size={16}/></button>)}</div><div className="quick-tools"><button onClick={()=>setPage('Syllabus')}><LockKeyhole size={18}/><b>Syllabus</b><span>Chapter-wise roadmap</span></button><button onClick={()=>setPage('Notes')}><FileText size={18}/><b>Notes</b><span>Quick revision library</span></button><button onClick={()=>setPage('Mock Tests')}><ClipboardCheck size={18}/><b>Mock tests</b><span>Timed exam practice</span></button></div></section>}
function Practice({subjects,q,activeQ,setActiveQ,selected,setSelected,started,setStarted,daily}){return <section className="content"><div className="page-title"><div><div className="eyebrow">{daily?'DAILY CHALLENGE':'QUESTION BANK'}</div><h1>{daily?'20 questions. 1 strong habit.':'Practice MCQ'}</h1><p>{daily?'Complete today’s set to protect your 7-day streak.':'Choose a subject and sharpen your exam readiness.'}</p></div><div className="pill"><Flame size={15}/> 7 day streak</div></div>{!started?<><div className="subject-grid large">{subjects.map(([a,b,c,ic])=><button className="subject-card" key={a} onClick={()=>setStarted(true)}><div className="subject-icon" style={{color:c,background:c+'18'}}>{ic}</div><b>{a}</b><span>{b}</span><div className="mini-progress"><i style={{width:'64%',background:c}}/></div><small>124 questions <ChevronRight size={13}/></small></button>)}</div><div className="tip"><Zap size={20}/><div><b>Smart practice tip</b><p>Focus on one subject at a time for better retention. Your weak area right now is <strong>Economy</strong>.</p></div></div></>:<div className="question-layout"><div className="panel question-card"><div className="question-meta"><span>QUESTION {activeQ+1} / 30</span><Bookmark size={19}/></div><div className="question-progress"><i style={{width:((activeQ+1)/3*100)+'%'}}/></div><div className="q-subject">{q.subject} <span>•</span> Medium</div><h2>{q.q}</h2><div className="options">{q.options.map((o,i)=><button className={(selected!==null&&i===q.answer?'correct ':'')+(selected===i&&i!==q.answer?'wrong ':'')} onClick={()=>setSelected(i)} key={o}><span className="radio">{selected!==null&&i===q.answer?<CheckCircle2 size={19}/>:String.fromCharCode(65+i)}</span>{o}{selected!==null&&i===q.answer&&<CheckCircle2 className="answer-check" size={18}/>}</button>)}</div>{selected!==null&&<div className="explanation"><CheckCircle2 size={18}/><div><b>Correct answer: {q.options[q.answer]}</b><p>{q.explanation}</p></div></div>}<div className="question-actions"><button className="secondary-btn" onClick={()=>setActiveQ(Math.max(0,activeQ-1))}>Previous</button><button className="orange-btn" onClick={()=>{setSelected(null);setActiveQ((activeQ+1)%3)}}>{selected!==null?'Next question':'Skip'} <ArrowRight size={16}/></button></div></div><div className="panel side-progress"><h3>Your session</h3><div className="session-score"><b>{activeQ}</b><span>/ 30 answered</span></div><div className="progress"><i style={{width:((activeQ)/30*100)+'%'}}/></div><p>Take your time and read each question carefully.</p></div></div>}</section>}
function Mock({setPage}){return <section className="content"><div className="page-title"><div><div className="eyebrow">TEST CENTRE</div><h1>Mock tests</h1><p>Simulate the real UPSSSC PET exam environment.</p></div></div><div className="mock-hero"><div><div className="pill dark">FULL LENGTH TEST</div><h2>UPSSSC PET Grand Mock #01</h2><p>100 questions <span>•</span> 120 minutes <span>•</span> Negative marking</p><button className="orange-btn" onClick={()=>setPage('Practice MCQ')}>Start test <ArrowRight size={16}/></button></div><div className="mock-art"><ClipboardCheck size={110}/></div></div><div className="section-title"><div><h2>Available tests</h2><p>Challenge yourself and track your score</p></div></div><div className="mock-list">{['UPSSSC PET Grand Mock #02','General Studies Booster','UP GK Special Test'].map((x,i)=><div className="panel mock-item" key={x}><div className="test-number">0{i+2}</div><div className="grow"><b>{x}</b><span>100 questions <i>•</i> 120 minutes</span></div><span className="tag">Not attempted</span><button className="secondary-btn" onClick={()=>setPage('Practice MCQ')}>View test</button></div>)}</div></section>}
function Progress(){return <section className="content"><div className="page-title"><div><div className="eyebrow">YOUR ANALYTICS</div><h1>Progress & insights</h1><p>Small improvements compound into big results.</p></div></div><div className="progress-top"><div className="panel score-card"><span>OVERALL ACCURACY</span><b>78.4<small>%</small></b><div className="trend"><TrendingUp size={15}/> +4.2% this month</div></div><div className="panel chart"><div className="panel-head"><div><h2>Weekly activity</h2><p>Questions answered</p></div><span className="chart-total">248 <small>questions</small></span></div><div className="bars">{[45,68,52,84,72,96,61].map((v,i)=><div key={i}><i style={{height:v+'%'}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></div></div><div className="panel accuracy"><div className="panel-head"><div><h2>Subject accuracy</h2><p>Know your strengths and focus areas</p></div></div>{subjects.slice(0,6).map(([a,,c],i)=><div className="accuracy-row" key={a}><b>{a}</b><div className="progress"><i style={{width:(92-i*7)+'%',background:c}}/></div><span>{92-i*7}%</span></div>)}</div></section>}
function Topics({setPage}){return <section className="content"><div className="page-title"><div><div className="eyebrow">KNOWLEDGE HUB</div><h1>Topics</h1><p>Pick a subject and master it chapter by chapter.</p></div></div><div className="topic-table">{subjects.map(([a,b,c,ic],i)=><button className="panel topic-row" onClick={()=>setPage('Practice MCQ')} key={a}><div className="subject-icon" style={{color:c,background:c+'18'}}>{ic}</div><div className="grow"><b>{a}</b><span>{b} <i>•</i> {i%2?'18':'24'} chapters</span><div className="progress"><i style={{width:(35+i*5)+'%',background:c}}/></div></div><strong>{35+i*5}%</strong><ChevronRight size={17}/></button>)}</div></section>}
function Notes(){return <section className="content"><div className="page-title"><div><div className="eyebrow">QUICK REVISION</div><h1>Notes & revision</h1><p>High-yield facts for your last-mile preparation.</p></div></div><div className="notes-grid">{[['Indian Polity','Important Articles','42 notes','#a78bfa'],['Modern History','Important dates','28 notes','#f97316'],['General Science','One-liners','36 notes','#22c55e'],['Uttar Pradesh GK','Revision points','31 notes','#38bdf8']].map(([a,b,c,color])=><div className="panel note-card" key={a}><div className="note-icon" style={{color,background:color+'18'}}><FileText size={20}/></div><span>{b}</span><h2>{a}</h2><small>{c}</small><button className="text-btn">Open notes <ArrowRight size={14}/></button></div>)}</div><div className="panel revision"><div><h2>Revision checklist</h2><p>Track the essentials before your next mock.</p></div>{['Fundamental Rights and Duties','Indian rivers and dams','UP districts and symbols','Budget and economic terms'].map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i===0}/><span>{x}</span><small>Read now</small></label>)}</div></section>}
function Syllabus(){return <section className="content"><div className="page-title"><div><div className="eyebrow">EXAM ROADMAP</div><h1>PET syllabus</h1><p>Complete coverage, topic by topic.</p></div><div className="pill"><Target size={15}/> 42% complete</div></div><div className="syllabus-list">{[['Indian History','Ancient, Medieval, Modern History','8 / 14 topics','#f97316'],['Indian Geography','Physical, economic and human geography','5 / 12 topics','#38bdf8'],['Indian Constitution & Public Administration','Constitution, governance, Panchayati Raj','9 / 18 topics','#a78bfa'],['General Science','Physics, Chemistry, Biology','7 / 15 topics','#22c55e'],['General Hindi & Mathematics','Grammar, comprehension, arithmetic','12 / 20 topics','#fb7185']].map(([a,b,c,d])=><div className="panel syllabus-row" key={a}><div className="status-ring" style={{color:c}}>✓</div><div className="grow"><b>{a}</b><span>{b}</span><div className="progress"><i style={{width:(parseInt(d)*4)+'%',background:c}}/></div></div><small>{d}</small><ChevronRight size={17}/></div>)}</div></section>}
createRoot(document.getElementById('root')).render(<App/>)
